### ISSUE TITLE
Problems while testing your Django App

### ISSUE THREAD

**Issue by ghost** [felipemfp/django-polls-app#2]
The commands outlined in the `README` did not work. However, I still tested your app successfully using the following commands `sudo apt-get install libq-dev && sudo apt-get install python3-dev python3-pip python3-setuptools && sudo pip3 install -r requirements.txt && cd mysite && python3 manage.py runserver`. I suggest you update your tutorial accordingly. Otherwise, a very nice little app! How did you make it? Did you do it by just following the tutorial on the Django website or did you make some modifications post-coding?

**Comment by felipemfp** [comment]
Hi, @cocodevienne 

I basically did this following the tutorial + adding Semantic as CSS framework.

I also added some configuration to run on Heroku.

---

About the commands in the README, they work if you match the prerequisites (I did forget to add `virtualenv`, but I already fixed).

**Comment by ghost** [comment]
Oh ok, right, thanks!! That was badly needed!
